jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/chat?serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  thymeleaf:
    enabled: true

  flyway:
    url: ${DB_URL:jdbc:mysql://localhost:3306/chat?serverTimezone=UTC}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    enabled: true
    schemas: chat
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: DEBUG