jwt:
  secret: ${SECRET}
  lifetime: 30m

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  thymeleaf:
    enabled: true

  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    schemas: chat
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: DEBUG